### ISSUE TITLE
hatflde.mod

### ISSUE THREAD

**Issue by syarra** [mpf/Optimization-Test-Problems#1]
There is an error in the mod file: hatflde 

Instead of 

```
param t {1..10};
param z {1..10}
```

it should be

```
param t {1..21};
param z {1..21}
```

And the `sum` in the objective function should be `sum {j in 1..21}`

**Comment by dpo** [comment]
Could you send a pull request?

**Comment by syarra** [comment]
sure!

**Comment by syarra** [comment]
PR #2
